### ISSUE TITLE
orderByValue, limitToLast

### ISSUE THREAD

**Issue by aaweb** [KallynGowdy/nativescript-plugin-firebase#2]
Hey Kallyn

Any plans on adding such functions? Just wanted to check since I saw there were some member variables like QueryLimitType on FirebaseCommon, so it you might be working on it already.

Andy

**Comment by KallynGowdy** [comment]
Hi Andy,

At this time, I do not have any immediate plans to add those functions as I do not think that I will be needing them. In addition, I don't think I will have time to implement them in the near future.

If you want to take a crack at it in a pull request I would be glad to help you out with any questions you may have.

Kal
