### ISSUE TITLE
Cannot read property 'authWithPassword' of undefined

### ISSUE THREAD

**Issue by calebeaires** [KallynGowdy/nativescript-plugin-firebase#3]
Evertying works well, except login type password. 

```
    firebase.login({
        // note that you need to enable email-password login in your firebase instance 
        type: firebase.LoginType.PASSWORD,
        email: 'myemail@gmail.com',
        password: 'mybigpass'
    }).then(function (result) {
        // the result object has these properties: uid, provider, expiresAtUnixEpochSeconds, profileImageURL, token 
        JSON.stringify(result);
    }, function (errorMessage) {
        console.log(errorMessage);
    });

```

Error: 

`Cannot read property 'authWithPassword' of undefined`

**Comment by KallynGowdy** [comment]
@calebeaires Can you tell me which platform that you are hitting this issue on?

**Comment by KallynGowdy** [comment]
@calebeaires Just published [Version 0.10.11](https://www.npmjs.com/package/nativescript-plugin-firebase-common) that should fix your issue.

**Comment by calebeaires** [comment]
Thanks for that! Do you intend to implemente Google login type?

**Comment by KallynGowdy** [comment]
@calebeaires At the moment, no. Good Google auth requires using Google Play Services on Android and the Google/SignIn pod, which are extraneous dependencies for this project. 

You could however implement that yourself and use the [`authWithOAuthToken()`](https://www.firebase.com/docs/web/api/firebase/authwithoauthtoken.html) function.
