### ISSUE TITLE
Navegate breaks app

### ISSUE THREAD

**Issue by calebeaires** [KallynGowdy/nativescript-plugin-firebase#4]
On using frame module I receive this error `Modifications to Config objects must occur before they are in use`. It seem I must [call it once](http://stackoverflow.com/questions/34464853/firebase-disk-persistence-error-modifications-to-config-objects-must-occur-bef). I have tried it, but I have no success.

**Comment by KallynGowdy** [comment]
Are you creating multiple instances of your firebase? This might happen if you call `Firebase.createNew()` whenever a page is opened. You can make sure that only one call is made by putting the creation code in its own module, like so:

``` typescript
// in a file called
// firebase.ts that is in your project
var Firebase = require("nativescript-plugin-firebase-common").Firebase;

export var firebase = Firebase.createNew({
  url: 'https://resplendent-fire-4211.firebaseio.com'
  // persist: false // turn off offline disk persistence
});
```

``` typescript
// in another file that is in the same directory as firebase.ts
var firebase = require("./firebase");

// use firebase
```

**Comment by calebeaires** [comment]
It work like a charm. 👍
