### ISSUE TITLE
New Firebase SDK blocks old login type

### ISSUE THREAD

**Issue by calebeaires** [KallynGowdy/nativescript-plugin-firebase#5]
Google (👎 ) starts to block old SDK. I prefer your plugin, but Google are not supporting when we use the new console.

```
Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/
```

**Comment by KallynGowdy** [comment]
@calebeaires 
If you already have a firebase.com account, you should be able to go to https://www.firebase.com/login/ and create a new project through there that will let you use version 2 of the SDK.

Right now I don't have the time to upgrade the project to Firebase v3. Obviously, you can switch over to using the other [NativeScript Firebase Plugin](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) (which this project is itself a fork of), or you could fork this project and try to upgrade it to version 3.

If you choose to fork this project and upgrade it to version 3, feel free to send a pull request and I'll include it in a new release.

More info about upgrading can be found at Google's Firebase website. ([iOS](https://firebase.google.com/support/guides/firebase-ios), [Android](https://firebase.google.com/support/guides/firebase-android))
